version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "jquery",
    "browser"
  ]
  style_guide = "google"
  dialect = "flow"

[[analyzers]]
name = "shell"
enabled = true

[[transformers]]
name = "black"
enabled = true
